@BaseApiUrl = http://localhost:7001/api
@FunctionKey = your-function-host-key
@ExcuseId = 1635bdd5-543f-4a28-88e6-e85de4cfdd1b


### Get all Excuses
GET {{BaseApiUrl}}/excuses
x-functions-key: {{FunctionKey}}


### Get Excuse by ID
GET {{BaseApiUrl}}/excuses/{{ExcuseId}}
x-functions-key: {{FunctionKey}}


### Get random Excuse
GET {{BaseApiUrl}}/excuses/random
x-functions-key: {{FunctionKey}}


### Create an Excuse
POST {{BaseApiUrl}}/excuses
x-functions-key: {{FunctionKey}}
Content-Type: application/json

{
  "text": "My code compiled itself out of spite."
}


### Update an Excuse
PUT {{BaseApiUrl}}/excuses/{{ExcuseId}}
x-functions-key: {{FunctionKey}}
Content-Type: application/json

{
  "text": "Aliens abducted my homework."
}


### Delete Excuse by ID
DELETE {{BaseApiUrl}}/excuses/{{ExcuseId}}
x-functions-key: {{FunctionKey}}
