name: Deploy Azure Functions

on:
  workflow_dispatch:
  push:
    paths:
      - "*.sln"
      - "src/**"

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Publish .NET Azure Function
        run: |
          dotnet publish serverless-excuses-azure/src/ServerlessExcuses.Api/ServerlessExcuses.Api.csproj \
            -c Release -o published
          cd published
          zip -r ../functionapp.zip .
          cd ..

      - name: Deploy to Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --src functionapp.zip
